version: '3.4'

services:
  nodejs:
    image: nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # NODE_ENV: production
      TZ: Asia/Bangkok
    ports:
      - 3031:3000
    stdin_open: true
    tty: true
    restart: unless-stopped