version: '3.4'

services:
  web:
    image: websocket-pcm
    container_name: websocket-pcm
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # NODE_ENV: production
      TZ: Asia/Bangkok
    volumes:
      - .:/usr/src/app
    ports:
      - 3030:3000
    stdin_open: true
    tty: true
    restart: unless-stopped